import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const data = ["Maçã", "Laranja", "Banana"];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Hello Hello!</div>

      {data.map((fruit, index) => (
        <div key={index}>{fruit}</div>
      ))}

      <Link href="/courses/pdm">
        <a>PDM</a>
      </Link>
    </div>
  );
};

export default Home;
